aglobal:
  resolve_timeout: 5m

route:
  receiver: 'discord-notifications'

receivers:
  - name: 'discord-notifications'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1352324645386452992/GXD_XorssSylFcqhOBxE5LqwLJivlsspCEulGUFzYnXk_4ImCx_-lPTEDgpNm0GF82vE'